### PR TITLE
Update delete script for cleanup in Workload Cluster

### PR DESCRIPTION
**Pull request by rupeshsahuoc**

### CODE REVIEW

**Review by snaiksat — CHANGES_REQUESTED** [review]
Since the script is getting longer, can we move this script to the scripts directory (call the script cleanup-control-cluster.sh) and provide a link from here to that script?

**Comment by rupeshsahuoc** [comment]
> Since the script is getting longer, can we move this script to the scripts directory (call the script cleanup-control-cluster.sh) and provide a link from here to that script?

Moved the script to scripts/cleanup-workload-cluster.sh, because this is used to clean workload cluster. And updated the README.

**Review by snaiksat — APPROVED** [review]

**Comment by snaiksat** [comment]
Can you push a similar change to the main branch?

**Comment by rupeshsahuoc** [comment]
> Can you push a similar change to the main branch?

Pushed here https://github.com/noironetworks/cko/pull/14

**Pull request merged**
